name: Conda Build Python 🐍 package, and Publish 🎉.

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - setup.py
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  conda_build:
    name: Build conda package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest]
        include:
          - os: ubuntu-latest
            target_platform: "linux-64"
          # - os: macos-latest
          #   target_platform: "osx-64"

    steps:
    - uses: actions/checkout@v2
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - uses: s-weigand/setup-conda@v1
      with:
        conda-channels: conda-forge

    - run: which conda
    - run: which andconda
    - run: conda install conda-build
    - run: which conda-build

    - name: Conda build nupyprop
      run: conda build -c conda-forge recipe

    # - name: Conda upload nupyprop
    #   run: anaconda upload -t ${{ secrets.ANACONDA_UPLOAD_TOKEN }} -v upload \
