name: Publish MacOS Python 🐍 distributions 📦 to TestPyPI 

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos-build-n-publish:
    name: Build and publish MacOS Python 🐍 distributions 📦 to TestPyPI
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Get history and tags for SCM versioning to work
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}      
    - name: Install build requirements
      run: |
        python3 -m pip install --upgrade pip build numpy setuptools setuptools_scm twine wheel
    - name: Python wheels MacOS build
      run: |
        F90=gfortran-11 python3 -m pip wheel -w dist --no-deps .
    - name: Publish to test-pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.test_pypi_secret }}
      run: |
        twine upload --repository testpypi dist/*
